### ISSUE TITLE
no CCLoader module on MacOS and iOS release

### ISSUE THREAD

**Issue by tavo1ga** [26F-Studio/Techmino#1036] opened 2023-11-09 01:08 UTC
Screenshot with unintended behaviors (*Image(s) Here*):
<img width="1120" alt="Screen Shot 8" src="https://github.com/26F-Studio/Techmino/assets/28776808/5c6df80f-4cb1-46b7-9234-5b13da530517">

If you can reproduce it, write the steps here. If you can't, try to describe what causes the unintended behavior, like pressing a key/button (*Details Here*):

1. open the game on iOS or MacOS
2. (optional) open Battle mode on Lunatic difficulty or above

**Comment by ImpleLee** [comment] 2023-11-09 13:39
Duplicate of #1023 ? On macOS it is fixed, but we don't know the situation on iOS... Can you provide more information about CC on iOS?

**Comment by ImpleLee** [comment] 2023-11-27 05:45
Our iOS CI breaks during last release, so we know your description is only suitable for macOS. Closing as duplicate...

**Closed by ImpleLee** 2023-11-27 05:45 UTC
Labels: bug, more info needed, iOS
