### ISSUE TITLE
Mojibake, Unsupported word: 「々」

### ISSUE THREAD

**Issue by AlphaIru** [26F-Studio/Techmino#609] opened 2022-01-19 10:32 UTC
The game will not recognize the word "々", which is used in Japanese for repetition of the last word. It would be very helpful if there is a support with this word.

**Comment by shoucandanghehe** [comment] 2022-01-19 10:39
This is caused by missing fonts and will be fixed in the next update

**Closed** 2022-01-20 05:10 UTC
Labels: bug
