### ISSUE TITLE
Where is legals.md???

### ISSUE THREAD

**Issue by SweetSea-ButImNotSweet** [26F-Studio/Techmino#983] opened 2023-09-21 05:46 UTC
## Screenshot with unintended behaviors (*Image(s) Here*):
![Screenshot_20230921-102242.jpg](https://github.com/26F-Studio/Techmino/assets/106439598/9460270e-bad6-40c7-8dc2-44e6c73f5341)

## If you can reproduce it, write the steps here. If you can't, try to describe what causes the unintended behavior, like pressing a key/button (*Details Here*):

Press (i) button then press Legal on Android release/snapshot builds

## Other note:
Assigns to ParticleG because this is caused by batch work in GitHub Action

**Comment by User670** [comment] 2023-09-21 09:54
Duplicate of #430

**Comment by SweetSea-ButImNotSweet** [comment] 2023-09-21 10:41
> Duplicate of #430 
> 
> edit: wait, #430 is closed? So it was once fixed, and reoccurred?

🤔 maybe

**Comment by shoucandanghehe** [comment] 2023-09-28 02:49
https://github.com/26F-Studio/Techmino/blob/75f3efc6a02d8cd5f714868076ab741ef0e3eb2b/.github/workflows/main.yml#L93
It looks like it's clearly not on the build list.
And should we also put license.txt into the game?

**Closed** 2023-09-28 03:53 UTC
Labels: fixed or duplicate, legal
