### ISSUE TITLE
Chromebook Debian Package does not Work.

### ISSUE THREAD

**Issue by AlphaIru** [26F-Studio/Techmino#851] opened 2023-02-05 22:11 UTC
Screenshot with unintended behaviors (*Image(s) Here*):

![image](https://user-images.githubusercontent.com/51223488/216848801-f168292d-a52e-4743-a69c-874ecdc2cb6e.png)

If you can reproduce it, write the steps here. If you can't, try to describe what causes the unintended behavior, like pressing a key/button (*Details Here*):
Trying to install the .deb Package onto the chromebook; it does not matter if the package is installed with "Files" (file explorer) or dpkg with Linux terminal (AKA penguin-terminal).  It still gives out the same error.

**Comment by shoucandanghehe** [comment] 2023-02-05 22:19
As far as I know, we don't have Chromebook users on the development team, so investigating this issue might be a little difficult.  
Have you tried AppImage?
If it works, you can use it temporarily until the issue is solved

**Comment by AlphaIru** [comment] 2023-02-14 09:59
Yeah... the AppImage works; however:

1: You have to run the command line by opening up the terminal everytime and type [.\Techmino_Linux.AppImage], there is no shortcut for Techmino which is very inconvinient.
2:
![Screenshot 2023-02-14 1 52 32 AM](https://user-images.githubusercontent.com/51223488/218701119-d65f31d9-9adc-4284-9c1c-5d29c5043914.png)
![image](https://user-images.githubusercontent.com/51223488/218701226-21e4c008-afd7-41ec-bd14-0d850755a692.png)

These two errors show up. 

Also to addition to the deb package: The error states:

airun@penguin:~$ sudo apt install ./techmino_Linux.deb

Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Note, selecting 'techmino' instead of './techmino_Linux.deb'
The following packages were automatically installed and are no longer required:
  bsdmainutils cpp-8 fonts-roboto fonts-roboto-unhinted libapt-inst2.0 libcodec2-0.8.1 libcroco3 libcrystalhd3 libcupsfilters1 libcupsimage2 libdns-export1104
  libdouble-conversion1 libicu63 libigdgmm5 libip4tc0 libip6tc0 libiptc0 libisc-export1100 libisl19 libjson-c3 libllvm7 liblzo2-2 libmpdec2 libnftables0 libperl5.28
  libprocps7 libpython3.7-minimal libpython3.7-stdlib libreadline7 libvpx5 libx264-155 libx265-165 libxcb-util0 ncal perl-modules-5.28 python3.7 python3.7-minimal
  squashfs-tools usb.ids
Use 'sudo apt autoremove' to remove them.
The following NEW packages will be installed:
  techmino
0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
Need to get 0 B/67.0 MB of archives.
After this operation, 0 B of additional disk space will be used.
Get:1 /home/airun/techmino_Linux.deb techmino amd64 0.17.12 [67.0 MB]
debconf: delaying package configuration, since apt-utils is not installed
dpkg-deb: error: archive '/home/airun/techmino_Linux.deb' uses unknown compression for member 'control.tar.zst', giving up
dpkg: error processing archive /home/airun/techmino_Linux.deb (--unpack):
 dpkg-deb --control subprocess returned error exit status 2
Errors were encountered while processing:
 /home/airun/techmino_Linux.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)

**Comment by shoucandanghehe** [comment] 2023-02-14 10:18
try `sudo apt update -y && sudo apt install zstd`
Looks like dpkg doesn't recognize .zst

**Comment by AlphaIru** [comment] 2023-02-14 14:45
Tried, but I don't see the fix...
![image](https://user-images.githubusercontent.com/51223488/218771539-f953477e-218c-4df4-92e7-980a48b94abe.png)

**Comment by ImpleLee** [comment] 2023-02-17 20:57
Seems the problem can be fixed by using different compression for .deb.
https://askubuntu.com/questions/1371692/build-deb-file-with-compress-tar-xz-not-tar-zst

**Comment by ImpleLee** [comment] 2023-02-17 20:58
cc @ParticleG

**Comment by shoucandanghehe** [comment] 2023-02-17 22:58
@AlphaIru hey😉 try this https://we.tl/t-TcsdAXNtQa

**Comment by AlphaIru** [comment] 2023-02-18 09:35
Good news and Bad news:

Good news: The package was successfully installed and worked "fine", and the save files were untouched. \(^u^)/

Bad news: CCloader error is persisting; I don't think it is a big deal but letting you guys know.

**Comment by shoucandanghehe** [comment] 2023-02-18 09:39
> Bad news: CCloader error is persisting; I don't think it is a big deal but letting you guys know.

Good news: The ColdClear error will be fixed at https://github.com/26F-Studio/cold_clear_ai_love2d_wrapper/pull/24
~~Just wait for the pr to merge and release a new version~~

**Comment by AlphaIru** [comment] 2023-02-18 09:47
Oh then that's completely okay then! I think the issue is resolved... but that means that you guys have to change the compression method right?

**Comment by shoucandanghehe** [comment] 2023-02-18 09:53
> Oh then that's completely okay then! I think the issue is resolved... but that means that you guys have to change the compression method right?

Yep, but only five characters need to be added to the command, ~~without even changing the code in the this repository (~~

> Nice beautiful icon.

This icon is exclusive to snapshot version, you will see another one in the release version

**Comment by shoucandanghehe** [comment] 2023-02-18 10:12
fix in https://github.com/love-actions/love-actions-linux/pull/2

**Closed by shoucandanghehe** 2023-02-18 10:12 UTC
Labels: bug, help wanted, hard, linux
