### ISSUE TITLE
custom game: board height 50 or more, coldclear bot, bot immediately spams hard drop to kill itself

### ISSUE THREAD

**Issue by BaronAWC95014** [26F-Studio/Techmino#686] opened 2022-04-24 17:38 UTC
Screenshot with unintended behaviors (*Image(s) Here*):
<img width="1110" alt="Screen Shot 2022-04-24 at 10 35 26 AM" src="https://user-images.githubusercontent.com/43506286/164989086-472354eb-df6b-4b5b-8fd9-096d58c4578f.png">
(board height is 100. bot is CC lvl 1, but it does the same on lvl 5 too, probably does the same for the other 3 levels)

If you can reproduce it, write the steps here. If you can't, try to describe what causes the unintended behavior, like pressing a key/button (*Details Here*):
1. make a custom game
2. set opponent to CC (level shouldn't matter, I only tested level 1 and 5)
3. set field height to 50 or more (only tested 50 and 100
4. start the game

**Comment by Trebor-Huang** [comment] 2022-04-24 17:59
ping @ImpleLee

**Comment by ImpleLee** [comment] 2022-04-28 02:47
Intended behavior since the internal board height in cold-clear is 40. We should show a warning if the height is too large when using cold-clear (it cannot work normally if h > 39 since upper borderline of the spawn block > 40).

side note: if the height is high enough (e.g. 38), a 2-line garbage is enough to kill cold-clear. We should also **show a warning** if board is nearly high enough to kill cold-clear. Maybe we should find someway in cold-clear to resolve that?

**Comment by ImpleLee** [comment] 2022-04-28 02:59
Internal discussion can also be found at https://github.com/orgs/26F-Studio/teams/techmino-cc-team/discussions/1 if we need somewhere to discuss after closing this issue.

**Comment by ImpleLee** [comment] 2022-05-02 10:09
ping @MrZ626

**Comment by C29H25N3O5** [comment] 2022-08-30 07:13
MrZ:

**Closed** 2023-10-22 17:51 UTC
Labels: enhancement, documentation
